# vi:syntax=dockerfile
FROM node:lts as builder
ARG VERSION=3.3.1
WORKDIR /
RUN npm install --save "git+https://github.com/standardnotes/web.git#${VERSION}" && \
    cd /node_modules/standard-notes-web && \
    rm -rf README.md LICENSE package.json docker Dockerfile log && \
    cd public/extensions && \
    rm -rf batch-manager/app extension-manager/app && \
    cd /node_modules && \
    find -type f \( -name "README.md" \
                    -o -name ".*" \
                    -o -name "webpack.config.js" \
                    -o -name "yarn.lock" \
                    -o -name "*.map" \) | xargs rm

FROM nginx:alpine
COPY --from=builder /node_modules/standard-notes-web/ /usr/share/nginx/html
