version: '2'

services:
  app:
    image: mcores/standardnote-app
    depends_on:
      - db
    env_file: .env
    links:
      - db
    ports:
      - "3000:3000"

  db:
    image: mariadb:10
    env_file: .env
    volumes:
      # - db_data:/var/lib/mysql
      - ./db:/var/lib/mysql

# volumes:
#   db_data:

